### ISSUE TITLE
Crash on MCPC server start.

### ISSUE THREAD

**Issue by Zaakjin** [mnn/jaffas#3]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/14/13 10:49 PM
Description: Exception in server tick loop

java.lang.VerifyError: (class: net/minecraft/world/WorldServer, method: func_72893_g signature: ()V) Register 11 contains wrong type
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:317)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 414851376 bytes (395 MB) / 872480768 bytes (832 MB) up to 1431699456 bytes (1365 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1536M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    CraftBukkit Information: 
   Running: CraftBukkit version git-MCPC-Plus-jenkins-MCPC-Plus-547 (MC: 1.5.2) (Implementing API version 1.5.2-R0.2-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Threads: { RUNNABLE DestroyJavaVM: [], WAITING Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:79), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], RUNNABLE Attach Listener: [], RUNNABLE Listen thread: [java.net.DualStackPlainSocketImpl.accept0(Native Method), java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source), java.net.AbstractPlainSocketImpl.accept(Unknown Source), java.net.PlainSocketImpl.accept(Unknown Source), java.net.ServerSocket.implAccept(Unknown Source), java.net.ServerSocket.accept(Unknown Source), net.minecraft.server.ServerListenThread.run(ServerListenThread.java:82)], RUNNABLE Signal Dispatcher: [], RUNNABLE Thread-6: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.dedicated.DedicatedServerCommandThread.run(DedicatedServerCommandThread.java:41)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:87)], TIMED_WAITING Thread-5: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServerSleepThread.run(SourceFile:60)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_5_R3.CraftCrashReport.call(CraftCrashReport.java:27), net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:106), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:59), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635), net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)],}
   Recent tasks from -31--1{}
    FML: MCP v7.51 FML v5.2.23.734 Minecraft Forge 7.8.0.734 11 mods loaded, 11 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{5.2.23.734} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{7.8.0.734} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore{0.8.7} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    monnef-core{0.4.21} [monnef Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Jaffas{0.4.22} [Jaffas and more!](mod_jaffas_0.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Jaffas-Trees{0.4.22} [Jaffas - Trees](mod_jaffas_0.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Jaffas-Technic{0.4.22} [Jaffas - Technic](mod_jaffas_0.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Jaffas-Power{0.4.22} [Jaffas - Power](mod_jaffas_0.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Jaffas-Xmas{0.4.22} [Jaffas - Xmas](mod_jaffas_0.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by mnn** [comment]
This is known issue (but on the other hand I have never claimed that our mod is compatible with MCPC+). The incompatibility might get fixed if/when we switch from ASM to Javassist (not before porting to MC1.6.\* is done).

http://www.jaffaswiki.tk/wiki/othermods#mcpc

**Comment by mnn** [comment]
Should be fixed in mnn/monnefcore@e9d27601cc2ae837751f692ae0fdadcc8b7c636b (it will be included in version 0.5.1).
